/**
 * RebeccaApiClient — resilient HTTP client for the Rebecca Panel Go backend.
 *
 * Key contracts:
 *  - Auth:        POST /api/admin/token  (JSON body: {username, password})
 *                 Response: {access_token, token_type}
 *                 Token is a custom HS256 JWT; expiry is panel-configured
 *                 (default 0 = no expiry). We refresh proactively 60s before
 *                 the exp claim, or after a 401 response.
 *
 *  - API key:     If REBECCA_API_KEY is set it is sent as "Authorization: Bearer <key>"
 *                 and no token fetch is ever attempted.
 *
 *  - Cloudflare 521 / 5xx resilience:
 *                 Any 5xx or network error is retried with full exponential
 *                 backoff (1 s → 2 s → 4 s …) up to MAX_RETRIES attempts.
 *                 After exhausting retries a RebeccaOriginDownError is thrown
 *                 so callers can distinguish "panel is down" from any other
 *                 API error and react accordingly (saga rollback, admin alert).
 *
 *  - Request shapes verified against Rebecca `dev` branch:
 *      POST   /api/user              body: UserCreate
 *      GET    /api/user/:username
 *      PUT    /api/user/:username    body: UserModify
 *      DELETE /api/user/:username    200 {username, status}
 *      POST   /api/user/:username/reset
 *      POST   /api/user/:username/revoke_sub
 *      GET    /api/users?offset&limit&search&status
 *
 *  - Response shape: UserDetail (all nullable fields are *int64 / *string in Go,
 *    i.e. null | number | string in JSON — typed as optional below).
 */

import { logger } from './logger.js';
import { validateRebeccaBaseUrl } from './rebeccaBaseUrl.js';
import type { ZodType } from 'zod';
import {
  rebeccaDeleteResponseSchema,
  rebeccaTokenResponseSchema,
  rebeccaUserDetailSchema,
  rebeccaUsersResponseSchema,
} from './RebeccaApiSchemas.js';

// ─── Typed errors ────────────────────────────────────────────────────────────

export class RebeccaApiError extends Error {
  public readonly endpoint: string;
  public readonly bodyLength: number;

  constructor(
    public readonly status: number,
    endpoint: string,
    body: string
  ) {
    const safeEndpoint = safeEndpointForLogs(endpoint);
    super(`Rebecca API [${status}] ${safeEndpoint}`);
    this.endpoint = safeEndpoint;
    this.bodyLength = body.length;
    this.name = 'RebeccaApiError';
  }
}

export class RebeccaContractError extends Error {
  public readonly endpoint: string;

  constructor(
    endpoint: string,
    public readonly issueCount: number,
    options?: ErrorOptions
  ) {
    const safeEndpoint = safeEndpointForLogs(endpoint);
    super(`Rebecca API contract mismatch on ${safeEndpoint}`, options);
    this.endpoint = safeEndpoint;
    this.name = 'RebeccaContractError';
  }
}

export class RebeccaOriginDownError extends Error {
  public readonly endpoint: string;

  constructor(
    endpoint: string,
    public readonly lastStatus: number | null,
    public readonly attempts: number,
    /** True when at least one retry may have left this process and its outcome is uncertain. */
    public readonly requestDispatched = false
  ) {
    const safeEndpoint = safeEndpointForLogs(endpoint);
    super(
      `Rebecca panel is unreachable (Cloudflare 5xx / origin down) after ${attempts} attempts on ${safeEndpoint}`
    );
    this.endpoint = safeEndpoint;
    this.name = 'RebeccaOriginDownError';
  }
}

// ─── API types (verified against internal/app/user/dto.go) ───────────────────

/** Valid statuses that can be set on create */
export type UserStatusCreate = 'active' | 'on_hold';

/** Valid statuses that can be set on update */
export type UserStatusModify = 'active' | 'disabled' | 'on_hold';

/** All statuses returned by the API */
export type UserStatus = 'active' | 'disabled' | 'limited' | 'expired' | 'on_hold' | 'deleted';

/** Full user detail response (GET /api/user/:username and mutation responses) */
export interface RebeccaUserDetail {
  username: string;
  status: UserStatus;
  used_traffic: number; // bytes
  lifetime_used_traffic: number;
  data_limit: number | null; // bytes, null = unlimited
  expire: number | null; // Unix seconds, null = never
  created_at: string;
  subscription_url: string;
  /**
   * All canonical subscription URL variants generated by Rebecca (key, token,
   * username-key, and configured aliases).  The Go API serializes this as
   * `subscription_urls`; `links` below contains proxy configuration links and
   * must not be used to validate a subscription URL.
   */
  subscription_urls?: Record<string, string>;
  links: string[];
  proxies: Record<string, Record<string, unknown>>;
  inbounds: Record<string, string[]>;
  note: string | null;
  telegram_id: string | null;
  sub_updated_at: string | null;
  online_at: string | null;
  ip_limit: number;
  service_id: number | null;
  service_name: string | null;
  admin_username: string | null;
}

/** Light item in the users list */
export interface RebeccaUserListItem {
  username: string;
  status: UserStatus;
  used_traffic: number;
  data_limit: number | null;
  expire: number | null;
  subscription_url: string;
  subscription_urls?: Record<string, string>;
  links: string[];
  online_at: string | null;
  created_at: string;
}

export interface RebeccaUsersResponse {
  users: RebeccaUserListItem[];
  total: number;
  status_breakdown: Record<string, number>;
}

type RebeccaSubscriptionCarrier = {
  subscription_url: string;
  subscription_urls?: Record<string, string>;
};

export interface RebeccaConnectionOptions {
  baseUrl: string;
  adminUsername?: string;
  adminPassword?: string;
  apiKey?: string;
}

/** Body for POST /api/user */
export interface RebeccaCreateUserPayload {
  username: string;
  /** Required by current Rebecca dev API: every user belongs to a service. */
  service_id: number;
  status?: UserStatusCreate;
  data_limit?: number | null; // bytes, 0 = unlimited
  expire?: number | null; // Unix seconds, 0 or null = never
  inbounds?: Record<string, string[]>;
  proxies?: Record<string, Record<string, unknown>>;
  note?: string;
  ip_limit?: number;
}

/** Body for PUT /api/user/:username */
export interface RebeccaUpdateUserPayload {
  status?: UserStatusModify;
  data_limit?: number | null;
  expire?: number | null;
  inbounds?: Record<string, string[]>;
  proxies?: Record<string, Record<string, unknown>>;
  note?: string;
  ip_limit?: number;
}

/** Response from DELETE /api/user/:username */
export interface RebeccaDeleteResponse {
  username: string;
  status: string;
}

// ─── Constants ───────────────────────────────────────────────────────────────

const MAX_RETRIES = 4;
const BASE_BACKOFF_MS = 1_000;
const MAX_BACKOFF_MS = 16_000;
const REQUEST_TIMEOUT_MS = 20_000;

/** HTTP status codes that indicate Cloudflare / origin-level failure */
const RETRYABLE_5XX = new Set([500, 502, 503, 504, 521, 522, 523, 524]);

// ─── JWT expiry decoder (no external dep) ────────────────────────────────────

function jwtExpiry(token: string): number | null {
  try {
    const parts = token.split('.');
    if (parts.length < 2) return null;
    const payload = JSON.parse(Buffer.from(parts[1]!, 'base64url').toString('utf8')) as {
      exp?: number;
    };
    return payload.exp ?? null;
  } catch {
    return null;
  }
}

// ─── Client ──────────────────────────────────────────────────────────────────

export class RebeccaApiClient {
  private baseUrl: string;
  private adminUsername: string;
  private adminPassword: string;
  private apiKey: string | undefined;

  private accessToken: string | null = null;
  /** Unix seconds — expire claim from JWT, or heuristic 24 h */
  private tokenExpiresAt: number = 0;

  constructor(options: RebeccaConnectionOptions) {
    this.baseUrl = validateRebeccaBaseUrl(options.baseUrl);
    this.adminUsername = options.adminUsername ?? 'admin';
    this.adminPassword = options.adminPassword ?? '';
    this.apiKey = options.apiKey;
  }

  /**
   * Apply live connection settings from the bot settings store. TLS remains
   * enforced by Node's native fetch implementation; insecure HTTP is rejected.
   */
  configure(options: Partial<RebeccaConnectionOptions>): void {
    if (options.baseUrl !== undefined) this.baseUrl = validateRebeccaBaseUrl(options.baseUrl);
    if (options.adminUsername !== undefined) this.adminUsername = options.adminUsername;
    if (options.adminPassword !== undefined) this.adminPassword = options.adminPassword;
    if (options.apiKey !== undefined) this.apiKey = options.apiKey || undefined;
    this.invalidateToken();
  }

  // ── Auth ───────────────────────────────────────────────────────────────────

  private async getAuthToken(): Promise<string> {
    if (this.apiKey) return this.apiKey;

    const nowSec = Math.floor(Date.now() / 1000);
    // Reuse if not expiring within 60 s
    if (this.accessToken && this.tokenExpiresAt > nowSec + 60) {
      return this.accessToken;
    }

    const url = `${this.baseUrl}/api/admin/token`;
    // Rebecca accepts JSON body (confirmed in admin_auth.go readAdminLoginRequest)
    const res = await this.fetchWithTimeout(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ username: this.adminUsername, password: this.adminPassword }),
    });

    if (!res.ok) {
      const errBody = await res.text();
      logger.error(
        { status: res.status, errorBodyLength: errBody.length },
        'Rebecca API: token fetch failed'
      );
      throw new RebeccaApiError(res.status, '/api/admin/token', errBody);
    }

    const data = await this.parseResponseJson<{ access_token: string; token_type?: string }>(
      res,
      '/api/admin/token',
      rebeccaTokenResponseSchema
    );
    const accessToken = data.access_token;
    this.accessToken = accessToken;
    // Parse expiry from JWT; fall back to 24 h
    const exp = jwtExpiry(accessToken);
    this.tokenExpiresAt = exp ?? nowSec + 86_400;
    return accessToken;
  }

  private invalidateToken(): void {
    this.accessToken = null;
    this.tokenExpiresAt = 0;
  }

  // ── Fetch with timeout ─────────────────────────────────────────────────────

  private fetchWithTimeout(url: string, init: RequestInit): Promise<Response> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    return fetch(url, { ...init, signal: controller.signal }).finally(() => clearTimeout(timer));
  }

  // ── Core request with retry + 521 resilience ───────────────────────────────

  private async request(
    endpoint: string,
    options: RequestInit = {},
    attempt = 0,
    requestDispatched = false
  ): Promise<unknown> {
    // Auth failing — propagate immediately, no retry
    const token = await this.getAuthToken();

    const url = `${this.baseUrl}${endpoint}`;
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: `Bearer ${token}`,
      ...(options.headers as Record<string, string>),
    };

    let res: Response;
    try {
      res = await this.fetchWithTimeout(url, { ...options, headers });
    } catch (networkErr: unknown) {
      // Network-level error (ECONNRESET, AbortError from timeout, etc.)
      return this.handleRetryableFailure(
        endpoint,
        options,
        attempt,
        null,
        networkErr,
        requestDispatched || networkFailureMayHaveDispatched(networkErr)
      );
    }

    // 401 — token may have expired; invalidate and retry once (no backoff)
    if (res.status === 401 && !this.apiKey) {
      if (attempt === 0) {
        this.invalidateToken();
        return this.request(endpoint, options, attempt + 1);
      }
      const body = await res.text();
      throw new RebeccaApiError(res.status, endpoint, body);
    }

    // 5xx Cloudflare/origin error — retryable with backoff
    if (RETRYABLE_5XX.has(res.status)) {
      return this.handleRetryableFailure(endpoint, options, attempt, res.status, null, true);
    }

    if (!res.ok) {
      const errBody = await res.text();
      logger.error(
        {
          status: res.status,
          endpoint: safeEndpointForLogs(endpoint),
          errorBodyLength: errBody.length,
        },
        'Rebecca API error'
      );
      throw new RebeccaApiError(res.status, endpoint, errBody);
    }

    // 204 No Content
    if (res.status === 204) return undefined;

    return this.readJson(res, endpoint);
  }

  private async handleRetryableFailure(
    endpoint: string,
    options: RequestInit,
    attempt: number,
    statusCode: number | null,
    networkErr: unknown,
    requestDispatched: boolean
  ): Promise<unknown> {
    const label = statusCode != null ? `HTTP ${statusCode}` : 'network error';
    logger.warn(
      {
        endpoint: safeEndpointForLogs(endpoint),
        attempt,
        statusCode,
        networkErrorName: networkErr instanceof Error ? networkErr.name : typeof networkErr,
      },
      `Rebecca API retryable failure (${label}), attempt ${attempt + 1}/${MAX_RETRIES + 1}`
    );

    if (attempt >= MAX_RETRIES) {
      throw new RebeccaOriginDownError(endpoint, statusCode, attempt + 1, requestDispatched);
    }

    const backoff = Math.min(BASE_BACKOFF_MS * 2 ** attempt, MAX_BACKOFF_MS);
    const jitter = Math.random() * 500;
    await new Promise((r) => setTimeout(r, backoff + jitter));

    return this.request(endpoint, options, attempt + 1, requestDispatched);
  }

  private async readJson(res: Response, endpoint: string): Promise<unknown> {
    try {
      return await res.json();
    } catch (err) {
      throw new RebeccaContractError(endpoint, 1, { cause: err });
    }
  }

  private parseContract<T>(endpoint: string, schema: ZodType<T>, payload: unknown): T {
    const parsed = schema.safeParse(payload);
    if (parsed.success) return parsed.data;

    logger.error(
      {
        endpoint: safeEndpointForLogs(endpoint),
        issueCount: parsed.error.issues.length,
        issues: parsed.error.issues.slice(0, 5).map((issue) => ({
          path: issue.path.join('.'),
          code: issue.code,
        })),
      },
      'Rebecca API response contract mismatch'
    );
    throw new RebeccaContractError(endpoint, parsed.error.issues.length, {
      cause: parsed.error,
    });
  }

  private async parseResponseJson<T>(
    res: Response,
    endpoint: string,
    schema: ZodType<T>
  ): Promise<T> {
    return this.parseContract(endpoint, schema, await this.readJson(res, endpoint));
  }

  // ── Public API methods ─────────────────────────────────────────────────────

  /** GET /api/user/:username → UserDetail */
  async getUser(username: string): Promise<RebeccaUserDetail> {
    return this.withAbsoluteSubscriptionUrls(
      this.parseContract<RebeccaUserDetail>(
        `/api/user/${encodeURIComponent(username)}`,
        rebeccaUserDetailSchema,
        await this.request(`/api/user/${encodeURIComponent(username)}`)
      )
    );
  }

  /**
   * GET /api/users?offset&limit&search&status
   * Returns {users, total, status_breakdown}
   */
  async getUsers(
    offset = 0,
    limit = 100,
    search?: string,
    status?: UserStatus,
    includeLinks = false
  ): Promise<RebeccaUsersResponse> {
    const q = new URLSearchParams({
      offset: String(offset),
      limit: String(limit),
    });
    if (search) q.set('search', search);
    if (status) q.set('status', status);
    if (includeLinks) q.set('links', 'true');
    const endpoint = `/api/users?${q.toString()}`;
    const result = this.parseContract<RebeccaUsersResponse>(
      endpoint,
      rebeccaUsersResponseSchema,
      await this.request(endpoint)
    );
    return {
      ...result,
      users: result.users.map((user) => this.withAbsoluteSubscriptionUrls(user)),
    };
  }

  /** POST /api/user → UserDetail (201 Created) */
  async createUser(payload: RebeccaCreateUserPayload): Promise<RebeccaUserDetail> {
    // Coerce 0 → null for data_limit/expire so the backend treats them as unlimited/never
    const body: Record<string, unknown> = {
      ...payload,
      status: payload.status ?? 'active',
      data_limit: payload.data_limit === 0 ? null : (payload.data_limit ?? null),
      expire: payload.expire === 0 ? null : (payload.expire ?? null),
    };
    return this.withAbsoluteSubscriptionUrls(
      this.parseContract<RebeccaUserDetail>(
        '/api/user',
        rebeccaUserDetailSchema,
        await this.request('/api/user', {
          method: 'POST',
          body: JSON.stringify(body),
        })
      )
    );
  }

  /** PUT /api/user/:username → UserDetail */
  async updateUser(
    username: string,
    payload: RebeccaUpdateUserPayload
  ): Promise<RebeccaUserDetail> {
    return this.withAbsoluteSubscriptionUrls(
      this.parseContract<RebeccaUserDetail>(
        `/api/user/${encodeURIComponent(username)}`,
        rebeccaUserDetailSchema,
        await this.request(`/api/user/${encodeURIComponent(username)}`, {
          method: 'PUT',
          body: JSON.stringify(payload),
        })
      )
    );
  }

  /**
   * DELETE /api/user/:username → {username, status}
   * Note: Rebecca returns 200 with a body, not 204.
   */
  async deleteUser(username: string): Promise<RebeccaDeleteResponse> {
    const endpoint = `/api/user/${encodeURIComponent(username)}`;
    return this.parseContract<RebeccaDeleteResponse>(
      endpoint,
      rebeccaDeleteResponseSchema,
      await this.request(endpoint, { method: 'DELETE' })
    );
  }

  /**
   * POST /api/user/:username/reset
   * Resets traffic counter; returns updated UserDetail.
   */
  async resetUserTraffic(username: string): Promise<RebeccaUserDetail> {
    return this.withAbsoluteSubscriptionUrls(
      this.parseContract<RebeccaUserDetail>(
        `/api/user/${encodeURIComponent(username)}/reset`,
        rebeccaUserDetailSchema,
        await this.request(`/api/user/${encodeURIComponent(username)}/reset`, { method: 'POST' })
      )
    );
  }

  /**
   * POST /api/user/:username/revoke_sub
   * Rotates the subscription key; returns updated UserDetail.
   */
  async revokeSubscription(username: string): Promise<RebeccaUserDetail> {
    return this.withAbsoluteSubscriptionUrls(
      this.parseContract<RebeccaUserDetail>(
        `/api/user/${encodeURIComponent(username)}/revoke_sub`,
        rebeccaUserDetailSchema,
        await this.request(`/api/user/${encodeURIComponent(username)}/revoke_sub`, {
          method: 'POST',
        })
      )
    );
  }

  /**
   * Enable/Disable helpers — both use PUT with status field only.
   * enableUser  → status: 'active'
   * disableUser → status: 'disabled'
   */
  async enableUser(username: string): Promise<RebeccaUserDetail> {
    return this.updateUser(username, { status: 'active' });
  }

  async disableUser(username: string): Promise<RebeccaUserDetail> {
    return this.updateUser(username, { status: 'disabled' });
  }

  /**
   * Health probe — hits the panel login endpoint with a GET check.
   * Does NOT throw; returns false on any failure (including 5xx/timeouts).
   * We do not rely on a dedicated /healthz because Rebecca's health endpoint
   * varies by deployment; the token endpoint always responds if the panel is up.
   */
  async checkHealth(): Promise<boolean> {
    try {
      const url = `${this.baseUrl}/api/admin/token`;
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 5_000);
      // Bare GET to the token endpoint is expected to return a non-2xx (likely 404/405 since the endpoint is POST-only).
      // Panel is up if we get ANY HTTP response outside the retryable-5xx set (treated as "panel reachable").
      const res = await fetch(url, {
        method: 'GET',
        signal: controller.signal,
      }).finally(() => clearTimeout(timer));
      return res.status < 500 || !RETRYABLE_5XX.has(res.status);
    } catch {
      return false;
    }
  }

  /**
   * Rebecca may return a relative subscription path such as `/sub/<token>`.
   * Telegram recipients need a complete, clickable HTTPS URL, so expand only
   * those relative values against the currently configured panel origin.
   */
  private withAbsoluteSubscriptionUrls<T extends RebeccaSubscriptionCarrier>(user: T): T {
    const subscriptionUrls = user.subscription_urls
      ? Object.fromEntries(
          Object.entries(user.subscription_urls).map(([name, url]) => [
            name,
            this.toAbsoluteSubscriptionUrl(url),
          ])
        )
      : undefined;

    return {
      ...user,
      subscription_url: this.toAbsoluteSubscriptionUrl(user.subscription_url),
      ...(subscriptionUrls ? { subscription_urls: subscriptionUrls } : {}),
    };
  }

  private toAbsoluteSubscriptionUrl(value: string): string {
    const trimmed = value.trim();
    if (!trimmed) return trimmed;
    try {
      return new URL(trimmed, `${this.baseUrl}/`).toString();
    } catch {
      // Preserve an unexpected value verbatim; the caller can retain its
      // existing fallback rather than failing a successful panel response.
      return value;
    }
  }
}

const PRE_DISPATCH_NETWORK_CODES = new Set([
  'ENOTFOUND',
  'EAI_AGAIN',
  'ECONNREFUSED',
  'ENETUNREACH',
  'EHOSTUNREACH',
  'UND_ERR_CONNECT_TIMEOUT',
]);

/**
 * Node fetch cannot expose an exact "first request byte written" event. Be
 * deliberately conservative: only errors that prove connection setup never
 * completed are treated as pre-dispatch. Timeouts, resets, and unknown network
 * failures may have happened after Rebecca committed the mutation.
 */
function networkFailureMayHaveDispatched(err: unknown): boolean {
  let current: unknown = err;
  for (let depth = 0; depth < 4 && current && typeof current === 'object'; depth += 1) {
    const record = current as { code?: unknown; cause?: unknown; name?: unknown };
    if (typeof record.code === 'string' && PRE_DISPATCH_NETWORK_CODES.has(record.code)) {
      return false;
    }
    if (record.name === 'AbortError') return true;
    current = record.cause;
  }
  return true;
}

/** Subscription credentials can appear in the targeted users-list search. */
function safeEndpointForLogs(endpoint: string): string {
  const [path, query] = endpoint.split('?', 2);
  if (!query) return endpoint;
  const params = new URLSearchParams(query);
  if (!params.has('search')) return endpoint;
  params.set('search', '[REDACTED]');
  return `${path}?${params.toString()}`;
}
